name: gps_tracker_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^6.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.5+1
  geolocator: ^10.1.0
  flutter_blue_plus: ^1.31.18
  permission_handler: ^11.3.1
  latlong2: ^0.9.1
  crypto: ^3.0.2
  flutter_secure_storage: ^8.0.0
  http: ^1.5.0
  sqflite: ^2.2.8
  path_provider: ^2.0.15
  path: ^1.8.3

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.2.0
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
